language: cpp

sudo: required
dist: focal
compiler: clang

install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install -y bazel gcc clang

script:
  - bazel test --curses=no //...:all

addons:
  apt:
    packages:
    - clang
    update: true
  homebrew:
    packages:
    - gcc@10
    update: true

notifications:
  email: false